### ISSUE TITLE
OPFS cache not working

### ISSUE THREAD

**Issue by piedukexyz** [autodesk-platform-services/aps-powerbi-tools#14]
When trying to enable the OPFS cache in the custom visual, I get the following error:

OPFSCache.ts:96 Failed to open OPFS cache directory TypeError: Cannot read properties of undefined (reading 'getDirectory')
    at #init (OPFSCache.ts:92:50)
    at new OPFSCache (OPFSCache.ts:85:39)
    at Object.doInitGeomWorker [as doOperation] (OtgLoadWorker.js:75:25)
    at WorkerMain.dispatch (MainWorker.js:41:16)
    at eval (MainWorker-web.js:11:16)

**Comment by yiskang** [comment]
It's similar to https://github.com/autodesk-platform-services/aps-powerbi-tools/issues/3.

Unfortunately, Power BI doesn't allow third parties to use FileSystem API in the Visual Card sandbox (iframe).
